# https://taskfile.dev

version: '3'

vars:
  # ----- User defined variables -----

  # Path to directory for Lean files (defaults to `Sequencelib/Synthetic`)
  OUTPUT_DIR: ""
  # Number of sequences to process
  MAX_SEQUENCES: 0
  # Start parameter for synthesize.py
  START: 0
  # End parameter for synthesize.py
  END: 10

  # ----- End of user defined variables -----

  # Avoid changing these variables. The corresponding tasks download or
  # git sync the files to these locations.

  # Downloaded file `solutions`
  SOLUTIONS_FILE_PATH: "{{.HOME}}/solutions"
  # Cloned git repository `doc-gen4-cache`
  DOC_GEN4_CACHE: "{{.HOME}}/doc-gen4-cache"
  # Cloned git repository `sequencelib-data`
  SEQUENCELIB_DATA: "{{.HOME}}/sequencelib-data"
  # Cloned git repository `oeisdata`
  OEISDATA_PATH: "{{.HOME}}/repos/oeisdata"

  RESULT_FILE: "{{.SEQUENCELIB_DATA}}/oeis_results_all.json"

  # Is this file needed?
  PYTHON_RESULT_FILE: "/tmp/oeis_python_results_all.json"

tasks:
  checkout-doc-gen4-cache:
    desc: Checkout cache of doc-gen4
    run: once
    cmds:
      - git clone git@github.com:provables/doc-gen4-cache.git {{.DOC_GEN4_CACHE}}
      - |
        cd {{.DOC_GEN4_CACHE}}
        dvc pull
    status:
      - test -d "{{.DOC_GEN4_CACHE}}/.git"

  checkout-sequencelib-data:
    desc: Checkout supporting data for Sequencelib
    run: once
    cmds:
      - git clone git@github.com:provables/sequencelib-data.git {{.SEQUENCELIB_DATA}}
      - |
        cd {{.SEQUENCELIB_DATA}}
        dvc pull
    status:
      - test -d "{{.SEQUENCELIB_DATA}}/.git"

  ensure-uptodate-doc-gen4-cache:
    desc: Ensure doc-gen4 cache is up-to-date with the remote
    run: once
    dir: "{{ .DOC_GEN4_CACHE }}"
    cmds:
      - git pull origin main
      - dvc pull
    status:
      - |
        git remote update
        test -z "$(git log main..origin/main --oneline)"
    deps:
      - checkout-doc-gen4-cache

  ensure-uptodate-sequencelib-data:
    desc: Ensure sequencelib-data is up-to-date with the remote
    run: once
    dir: "{{.SEQUENCELIB_DATA}}"
    cmds:
      - git pull origin main
      - dvc pull
    status:
      - |
        git remote update
        test -z "$(git log main..origin/main --oneline)"
    deps:
      - checkout-sequencelib-data

  ensure-doc-gen4-cache:
    desc: Ensure doc-gen4 cache is available for building the page
    run: once
    cmds:
      - rsync -a --exclude='.git' {{.DOC_GEN4_CACHE}}/ .lake/build/doc/
    deps:
      - ensure-uptodate-doc-gen4-cache
    status:
      - test -z "$(rsync -ani --exclude='.git' --out-format='%i' {{.DOC_GEN4_CACHE}}/ .lake/build/doc/)"

  ensure-update-docs-cache-git:
    desc: Ensure the cache for update-docs.py is full
    run: once
    dir: "{{.SEQUENCELIB_DATA}}"
    vars:
      CACHE:
        sh: "$PYTHON scripts/update_docs.py --where-is"
    cmds:
      - cp oeis_data.json lean_oeis_info.json {{.CACHE}}
    sources:
      - oeis_data.json
      - lean_oeis_info.json
    generates:
      - "{{.CACHE}}/oeis_data.json"
      - "{{.CACHE}}/lean_oeis_info.json"
    deps:
      - ensure-uptodate-sequencelib-data

  ensure-update-docs-cache:
    desc: Ensure the cache for update_docs.py is populated by creating data locally [EXPENSIVE]
    run: once
    vars:
      CACHE:
        sh: "$PYTHON scripts/update_docs.py --where-is"
    cmds:
      - "$PYTHON scripts/update_docs.py --only-data"
    sources:
      - scripts/update_docs.py
      - Sequencelib/**/*.lean
      - exclude: Sequencelib/Meta/**/*.lean
      - exclude: Sequencelib/Defs/**/*.lean
    generates:
      - "{{ .CACHE }}/oeis_data.json"

  build:
    desc: Build the library
    cmds:
      - lake build
    deps:
      - get-cache

  lint:
    desc: Run linter
    cmds:
      - lake lint
    deps:
      - get-cache
      - build

  build-docs:
    desc: Build docs
    run: once
    sources:
      - ./**/*.lean
      - ./**/lakefile.toml
      - ./scripts/update_docs.py
      - ./scripts/values.html.j2
      - ./scripts/doc_index.html.j2
      - exclude: ./**/.lake
    generates:
      - .lake/build/doc/Sequencelib.html
      - home_page/sequences.md
    cmds:
      - DOCGEN_SRC="file" lake -R -Kenv=dev build Sequencelib:docs
      - "$PYTHON scripts/update_docs.py"
    deps:
      - get-cache
      - ensure-doc-gen4-cache

  serve-docs:
    desc: Serve docs
    cmds:
      - "$PYTHON -m webbrowser file:///$(pwd)/.lake/build/doc/Sequencelib.html"
    deps:
      - build-docs

  build-blueprint:
    desc: Build blueprint
    sources:
      - blueprint/src/content.tex
      - blueprint/src/chapter/*.tex
      - exclude: blueprint/print/**/*
      - exclude: blueprint/web/**/*
    generates:
      - blueprint/print/print.pdf
      - blueprint/web/index.html
    cmds:
      - leanblueprint pdf
      # For some reason, leanblueprint web generates files without write permissions,
      # so we need to delete any previous run.
      - rm -rf blueprint/web
      - leanblueprint web
    deps:
      - build-docs

  build-page:
    desc: Build full home page
    sources:
      - ./**/*.lean
      - ./lakefile.toml
      - blueprint/src/*
      - home_page/**/*
      - exclude: home_page/_site/**/*
      - exclude: home_page/blueprint/**/*
      - exclude: home_page/blueprint.pdf
      - exclude: home_page/docs/**/*
    generates:
      - home_page/_site/index.html
      - home_page/sequences.md
    cmds:
      - cp blueprint/print/print.pdf home_page/blueprint.pdf
      - rsync -av blueprint/web/ home_page/blueprint/
      - rsync -av .lake/build/doc/ home_page/docs
      - cd home_page && bundle install && bundle exec jekyll build
    deps:
      - build-docs
      - build-blueprint

  serve-page:
    desc: Serve full home page
    cmds:
      - cd home_page && bundle install && bundle exec jekyll serve
    deps:
      - build-page

  get-cache-for-dir:
    internal: true
    run: once
    dir: '{{.DIR | default "." }}'
    cmds:
      - lake exe cache get
    status:
      - test -f .lake/packages/mathlib/.lake/build/lib/lean/Mathlib.olean
  
  get-cache:
    desc: Ensure Mathlib cache is available
    cmds:
      - for: ["."]
        task: get-cache-for-dir
        vars:
          DIR: '{{ .ITEM }}'

  update-nolints:
    desc: Update nolints
    cmds:
      - lake exe batteries/runLinter --update

  render-sequencelib-lean:
    desc: Regenerate top-level Sequencelib.lean
    cmds:
      - "$PYTHON scripts/generate_imports.py"
    sources:
      - Sequencelib/**/*.lean
      - exclude: Sequencelib/Meta/**/*.lean
      - exclude: Sequencelib/Defs/**/*.lean
    generates:
      - Sequencelib.lean

  ensure-oeisdata:
    desc: Ensure there is a local clone of oeisdata
    run: once
    cmds:
      - git clone git@github.com:oeis/oeisdata.git {{.OEISDATA_PATH}}
    status:
      - test -d {{.OEISDATA_PATH}}/.git

  ensure-uptodate-oeisdata:
    desc: Ensure oeisdata is up-to-date with the remote
    run: once
    dir: "{{.OEISDATA_PATH}}"
    cmds:
      - git pull origin main
    deps:
      - ensure-oeisdata
    status:
      - |
        git remote update
        test -z "$(git log main..origin/main --oneline)"

  where-is-cache:
    desc: Display location of the update_docs cache
    cmds:
      - "$PYTHON scripts/update_docs.py --where-is"
    silent: true

  ensure-solutions:
    desc: Retrieve solutions file
    run: once
    cmds:
      - |
        wget -O {{.SOLUTIONS_FILE_PATH}} -q \
        https://raw.githubusercontent.com/barakeel/oeis-synthesis/refs/heads/main/src/results/solutions
    status:
      - test -f "{{.SOLUTIONS_FILE_PATH}}"

  oeis-py:
    method: timestamp
    desc: Run oeis.py
    cmds:
      - "$PYTHON scripts/oeis.py"
    env:
      OEIS_INSTALL: "{{.OEISDATA_PATH}}"
      RESULT_FILE: "{{.RESULT_FILE}}"
      PYTHON_RESULT_FILE: "{{.PYTHON_RESULT_FILE}}"
      MAX_SEQUENCES: "{{.MAX_SEQUENCES}}"
    sources:
      - scripts/oeis.py
    generates:
      - "{{.RESULT_FILE}}"
      - "{{.PYTHON_RESULT_FILE}}"
    deps:
      - ensure-uptodate-oeisdata

  synthesize-py:
    method: timestamp
    desc: Run synthesize.py
    cmds:
      - "$PYTHON scripts/synthesize.py -s {{.START}} -e {{.END}}"
    env:
      ALL_OEIS_RESULTS_FILE: "{{.RESULT_FILE}}"
      SOLUTIONS_FILE_PATH: "{{.SOLUTIONS_FILE_PATH}}"
      OUTPUT_DIR: "{{.OUTPUT_DIR}}"
    sources:
      - scripts/synthesize.py
      - scripts/oeis.py
      - "{{.RESULT_FILE}}"
      - "{{.SOLUTIONS_FILE_PATH}}"
    generates:
      - Sequencelib/Synthetic/*.lean
    deps:
      - oeis-py
      - ensure-uptodate-oeisdata
      - ensure-solutions